### ISSUE TITLE
bug: Pixel padding makes pixels width and height uneven

### ISSUE THREAD

**Issue by JSLegendDev** [kaplayjs/kaplay#110]
![image](https://github.com/marklovers/kaplay/assets/128189209/132977be-cf21-471d-9162-a496d606a7a4)

When displaying a sprite, all pixels do not have the same width and height. As discussed with @mflerackers on discord this is due to padding added by Kaplay.

Expected behavior : every pixel of a sprite should have the same size

**Comment by lajbel** [comment]
I don't think is due to the padding added by KAPLAY but maybe is a rendering stuff

**Comment by lajbel** [comment]
Do you have an example where can I test on that case?
