### ISSUE TITLE
feat: A way to be able to see the properties a GameObj has on debug.inspect

### ISSUE THREAD

**Issue by niceEli** [kaplayjs/kaplay#17]
### Discussed in https://github.com/marklovers/kaplay/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **amyspark-ng** May 22, 2024</sup>
Let's say my obj has a property speed, that i access doing obj.speed, i'd like to be able to see it in the debug.inspect window when you hover on it, not only the properties Comps return but properties that i myself have added</div>

**Comment by amyspark-ng** [comment]
i'd like to take a stab at this one! might be not too hard

**Comment by niceEli** [comment]
> i'd like to take a stab at this one! might be not too hard

ill add you as assignee then

**Comment by amyspark-ng** [comment]
kewl!!

**Comment by niceEli** [comment]
![image](https://github.com/marklovers/kaplay/assets/78963198/6ed5a95a-67e5-4eaa-9639-faf4580fb42b)

**Comment by amyspark-ng** [comment]
feels like we need to work in a "ui" for the debug inspect, where you can click objs to see their properties, could do something similar to the debugger that exists in haxeflixel, which i think is very nice
https://haxeflixel.com/documentation/debugger/

![debugger-overlay](https://github.com/marklovers/kaplay/assets/92493175/037945c1-5560-48b8-a7ce-1d17ccda7de6)
