### ISSUE TITLE
bug: Init of KAPLAY is slow

### ISSUE THREAD

**Issue by SpcFORK** [kaplayjs/kaplay#174]
### A clear and concise description of what the bug is.

Initial load of KAPLAY is very task heavy.

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/marklovers/kaplay/assets/126259962/1964eb02-3475-4055-97f8-1c6eb1f748e9)
![image](https://github.com/marklovers/kaplay/assets/126259962/a7d0d04a-2bb3-4fe1-8eed-afe0fb20689a)
![image](https://github.com/marklovers/kaplay/assets/126259962/ff2e58aa-7a51-4dfd-859c-99ca1e03a2f6)
![image](https://github.com/marklovers/kaplay/assets/126259962/7ce297ec-78b3-43af-b6ed-e953e702ebd9)

**Comment by lajbel** [comment]
Recently there was a refactor, how it goes now?

**Comment by SpcFORK** [comment]
I will check

**Comment by SpcFORK** [comment]
![image](https://github.com/user-attachments/assets/9388168b-4917-463e-9770-6e7ab712e634)

**Comment by lajbel** [comment]
Working on that, but is too general? Closing for now
