### ISSUE TITLE
bug: object disappears randomly

### ISSUE THREAD

**Issue by appsdevpk** [kaplayjs/kaplay#181]
## **Describe the bug**
I followed the documents on the site and built the sample game successfully. But a very strange thing is happening, the bean object disappears randomly when touching the ground on load or during game play. I am using firefox latest version on windows 10.
Here is my code, https://gist.github.com/appsdevpk/27d199c654e9bd2d89f3c226d126b224
## **Version**
v3001
## **To Reproduce**
create the basic game from docs and open in firefox.
### Steps to reproduce the behavior:

1.

## **Expected behavior**
the object should stay on screen

**Comment by appsdevpk** [comment]
issue resolved on 1000 gravity. More than 1000 gravity causing the issue

**Comment by appsdevpk** [comment]
first time the gravity was 1600, and its still disappearing after lowering the gravity to 1000, here is the video of game play.
https://drive.google.com/file/d/1mcuZjnS7-Z1Wyeb8IW2Q7uh2tp_1phCc/view?usp=sharing

**Comment by mflerackers** [comment]
Is it just the movie? or does it run that slow? Also, what are the coordinates of the bean when it disappears?

**Comment by appsdevpk** [comment]
its just the movie, i cannot find the coordinates when it disappears

**Comment by lajbel** [comment]
it looks a framerate on your end problem, can you tell us the frame rate (F1 for debug mode) also debug log every frame the player position will help too

**Comment by lajbel** [comment]
Also browser and device help too

**Comment by appsdevpk** [comment]
here is the pos i got, { x: 528.1152000000111, y: 317796.730481202 }

**Comment by mflerackers** [comment]
Do you have the pos.y and vel.y right when it leaves the screen? That y looks very large.

**Comment by appsdevpk** [comment]
yes thats the right one, and the velocity i am getting is { x: 0, y: 36519.520000000346 }, besides this issue, the lib is awesome, i have tried many libs before and never found any interesting lib

**Comment by mflerackers** [comment]
Try making the floor 480 pixels high instead of 48. You're tunneling through the floor and then gaining speed I think. This is due to having a low frame rate. what is weird though, is that there is a velocity limit, so it is impossible to reach the velocity you get if you were using kaplay. Are you sure you are not using kaboom?

**Comment by appsdevpk** [comment]
i am using kaplay from cdn (https://unpkg.com/kaplay@3001.0.0-alpha.17/dist/kaboom.js), i changed the floor height to 430 but still having the same issue

**Comment by lajbel** [comment]
it's a strange error, mostly with your system and browser, can you test in another browser if it happens too?

**Comment by lajbel** [comment]
any update?

**Comment by lajbel** [comment]
MF limited dt also made some changes to physics, this kind of errors should be fixed, if it's  not, please reopen.
