### ISSUE TITLE
bug: bodies fall through floor immediately at startup

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#275]
## **Describe the bug**

I'm creating a tile-map based **platformer** - levels made using `addLevel()`, and for right now, I'm using `rect()` and `color()` for the tiles since I don't have any sprites.

When I have tiles that get the `body()` and `area()` component (for example boxes that can be pushed around), if they are sitting on the floor at startup they fall straight through it even though the floor tiles also have `area()` and `body({ isStatic: true })`.

The same thing happens with the player except since I grab a reference to it I can just kludge the velocity to make sure it won't fall through the floor before the game even starts. (... this only works some of the times, I'm not sure why it behaves differently every time I reload, I would expect it to either always work or never work.)

## **Version**

`3001.0.0-alpha.18`

### Steps to reproduce the behavior:

Paste this code into kaplayground:

```js
// cSpell: ignore kaplay

kaplay({
    crisp: true,
    scale: 4,
    background: "#000000"
});


setGravity(300);

const level = addLevel([
    "##########################",
    "#                        #",
    "#                        #",
    "#       #####            #",
    "# @                      #",
    "#       ^^    ############",
    "###############           "
], {
    tileWidth: 16,
    tileHeight: 16,
    pos: vec2(20, 20),
    tiles: {
        "@": () => [
            rect(15, 15),
            area(),
            body({ jumpForce: 150, maxVelocity: 400 }),
            anchor("center"),
            color("#ff0000"),
            z(Infinity),
            "player"
        ],
        "^": () => [
            rect(15, 15),
            area(),
            anchor("center"),
            color("#ffff00"),
            body(),
            "coin"
        ],
        "#": () => [
            rect(16, 16),
            area(),
            body({ isStatic: true }),
            anchor("center"),
            color("#0000ff"),
            "ground"
        ],
    }
});

const player = level.get("player")[0];
// ?!? hacky ?!?
player.vel = vec2(0, -150);


onKeyDown("up", () => {
    if (player.isGrounded()) {
        player.jump();
    }
});

const SPEED = 64;

onKeyDown("left", () => {
    player.move(-SPEED, 0);
});

onKeyDown("right", () => {
    player.move(SPEED, 0);
});
```

or use this html:

```html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://unpkg.com/kaplay@3001.0.0-alpha.18/dist/kaplay.js"></script>
        <script src="main.js" defer></script>
    </head>
    <body>
        <!-- Nothing to see here. -->
    </body>
</html>
```

## **Expected behavior**

The player should not immediately fall through the floor when the game loads, nor should any of the other non-static bodies.

**Comment by mflerackers** [comment]
You give your player an immediate velocity of 150 pixels down, not an acceleration. This means the next frame your player is at the other side of the floor.
Use setGravity instead to use an acceleration instead.

**Comment by niceEli** [comment]
another fix would be to do your logic in 

```ts
onload(() => {
  // stuff here
})
```
as that waits for load before actually doing anything

**Comment by mflerackers** [comment]
I can't see this bug happening in the kaplayground. Is it because the frame rate is too low during load, and therefore too much distance is traveled during one frame?

**Comment by dragoncoder047** [comment]
> You give your player an immediate velocity of 150 pixels down, not an acceleration. This means the next frame your player is at the other side of the floor.

No, it's -150 pixels/sec down, or 150 pixels/sec up. 

> Use setGravity instead to use an acceleration instead.

I did - 300 - before the addLevel() call, and if I make it low enough that stuff doesn't tunnel through the floor, then jumping takes way too long

> another fix would be to do your logic in
> 
> ```js
> onload(() => {
>   // stuff here
> })
> ```
> 
> as that waits for load before actually doing anything

I made the script `defer`, that seems to have the same effect. (does it?)

> I can't see this bug happening in the kaplayground. Is it because the frame rate is too low during load, and therefore too much distance is traveled during one frame?

Could be, my computer is really crappy and so I am only getting about 10 FPS when debug mode is turned on and 20 with it off.

---

Out of interest, are you using an external library for physics?

**Comment by mflerackers** [comment]
No, we're using our own physics. The plan is to support multiple physics engines in order to fit different use cases. The current physics engine has some trouble, but I think the problem here may be the large dt used right after loading. I am planning to put the physics on a different, fixed, time step, which should solve this.

**Comment by dragoncoder047** [comment]
> The plan is to support multiple physics engines in order to fit different use cases.

That is a good idea!

> I think the problem here may be the large dt used right after loading. I am planning to put the physics on a different, fixed, time step, which should solve this.

That might work, but if you end up just picking .016 seconds (= 60 FPS) as the dt, and then the graphics end up lagging down to 20 FPS (like my case), then the physics will also slow down lag equally. This in effect means the game would just be running slower, which might give a player an advantage.

Or would the physics loop be independent of the frame loop?

- - -

I think that for the time being while you’re working on trying to integrate third-party physics engines, adding continuous collision detection to your homebrew physics might just solve this problem.

Since it would be a fairly expensive computation, CCD could be put behind a `{ bullet: true }` flag in the body component. It also might help to automatically turn it on  for every body if the frame rate drops too low. 

The algorithm is simple, but might be computationally expensive:

1. Find the convex hull of the original polygon’s points and the new position’s points
2. If this convex hull doesn’t overlap with any other bodies, stop, you’re done
3. Of the overlapping bodies, find the body that is closest to the original position
4. Find the exact dt at which the collision occurs by using binary search
5. Call the collision handler functions using that new dt and collision object

**Comment by mflerackers** [comment]
Independent, like Unity's fixedUpdate for example.
CCD is planned, but using Minkowski sums, since you don't need binary search and can just compute the exact moment in time where the collision will happen.

**Comment by mflerackers** [comment]
We will fix everything eventually, but there is a lot of work to do.
Some of it is planned for 4000 since it takes too many changes and might not be 100% backwards compatible.
But eventually we'll have quadtrees to speed up picking and collision, multiple physics engines to choose from, much faster graphics, global sorting and a lot of other fixes and optimizations. We only need some time.

**Comment by niceEli** [comment]
fixed update was added in #284 when a new npm version releases then you will have access to the feature

**Comment by lajbel** [comment]
will close for now, if error persist, reopen

**Comment by dragoncoder047** [comment]
I think it was just a lag issue anyway.
