### ISSUE TITLE
feat: multiple virtual buttons associated with physical input key

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#286]
I am making a platformer game that allows the player to jump *and* climb ladders. The controls associated with each have overlaps -- for example you can use space, w, or up to jump when walking normally not on a ladder, or you can use w or up to climb upwards when on a ladder, and the state (on ladder or off ladder) can be manually toggled by the player as well with another button.

I na&iuml;vely thought that just adding the keybindings in the global kaplay options would work, so I wrote this:

```js
kaplay({
    // snip
    buttons: {
        jump: {
            keyboard: ["w", "up", "space"],
            gamepad: ["south"]
        },
        move_up: {
            keyboard: ["w", "up"],
        },
        // snip
    }
});
```

... and then I wrote some code and wondered "why isn't my onButtonDown handler for `move_up` ever being called?"

The reason is that Kaplay just stops the first virtual button that includes the physical button that was just pressed, and doesn't bother to look further.

## **Describe the solution you'd like**

Simple: anywhere the functions that look up what virtual button a particular input event is associated with are called, they can be changed so they return an array of matching buttons instead of just the first one:

https://github.com/kaplayjs/kaplay/blob/c6ca658a03a86bc58af2f2b89b2b4f07156e9e00/src/app/app.ts#L943-L950

So the return type of `getButtonNameByKey` is currently `string | undefined`, perhaps it can be changed to `string[]`, and then line 947 can be replaced with something like this:
```ts
getButtonNamesByKey(k).forEach(btn => state.buttonState.press(btn));
```

## **Describe alternatives you've considered**

I don't need to or want to use a scene to do this switching - it's literally just one global boolean variable that some event handlers look at.

**Comment by lajbel** [comment]
So the problem is no multiple keys being detected in a onButton event? Sorry, I didn't understand what's the problem

**Comment by dragoncoder047** [comment]
In the example above, I have two buttons -- `jump` and `move_up` -- that are associated with the physical up key on my keyboard, but when I press the up key, only the `jump` handler fires.

**Comment by lajbel** [comment]
Oh I got it, will fix!

**Comment by lajbel** [comment]
Can you try installing that PR **Only for test if the bug is fixed**, the second comment has the instructions for installing

**Comment by dragoncoder047** [comment]
i'm very stupid, PR #908 reintroduced this bug.

thankfully since it's my fault I know exactly what I need to fix, will open that PR tomorrow
