### ISSUE TITLE
bug: conflicts between `navigation()` and Safari's `navigation()`

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#289]
## **Describe the bug**

This bug does not occur in Chrome or Firefox, it only occurs in Safari. The game just fails to load.

## **Version**

3001.0.0-alpha.19 loaded from unpkg.

## **To Reproduce**

Call kaplay(). That's it!!

## **Expected behavior**

The game works!

## **Screenshots**

<img width="1076" alt="Screenshot 2024-07-28 at 1 58 19 PM" src="https://github.com/user-attachments/assets/d813de77-6210-487e-a183-f41c355b2035">

**Comment by lajbel** [comment]
will further test, I don't have Safari lol, that's the only problem

**Comment by lajbel** [comment]
can you disable globals and test if it works?

**Comment by dragoncoder047** [comment]
Same error with `globals: false`.

**Comment by lajbel** [comment]
Is global: false in kaplay({})

**Comment by niceEli** [comment]
Testing KAPLAY alpha 18.1 on iOS/iPadOS Safari I don't have this issue

**Comment by niceEli** [comment]
After further testing on alpha 19.1 there also seems to be no issues. What version of kaplay are you using?

**Comment by dragoncoder047** [comment]
Im using whatever loads from https://unpkg.com/kaplay@3001.0.0-alpha.19.1/dist/kaplay.js -- 3001alpha19.1, I guess. And I am on Mac Safari, not iPad.

**Comment by dragoncoder047** [comment]
> Is **global**: false in kaplay({})

never mind, this fixes the "read only property" error.

**Comment by lajbel** [comment]
It was to confirm what is related to the error, will investigate more

**Comment by lajbel** [comment]
It still happens?

**Comment by dragoncoder047** [comment]
> It still happens?

hang on, will test

**Comment by dragoncoder047** [comment]
> > It still happens?
> 
> hang on, will test

yes

and this is with bleeding edge from #301

**Comment by lajbel** [comment]
I don't have a safari device (only iPhone) so it's kinda hard to test but the bug seems to be here:

kaplay.ts 1326

```js
    if (gopt.global !== false) {
        for (const key in k) {
            (<any> window[<any> key]) = k[key as keyof KAPLAYCtx];
        }
    }
```

**Comment by lajbel** [comment]
Maybe window is readonly in Safari? or we are assigning a readonly prop that's present only on Safari?

**Comment by dragoncoder047** [comment]
I figured out what is the problem: `navigation()` conflicts with the [Navigation API](https://developer.mozilla.org/en-US/docs/Web/API/Window/navigation) that can be enabled in Safari with a feature flag (I have it turned on and it must be readonly).

I found it by adding:
```diff
    if (gopt.global !== false) {
        for (const key in k) {
+           console.log("adding key:", key);
            (<any> window[<any> key]) = k[key as keyof KAPLAYCtx];
        }
    }
```

and I got

<img width="571" alt="Screenshot 2024-09-07 at 3 01 02 PM" src="https://github.com/user-attachments/assets/8b735aa1-d7a6-47dc-86e7-25e121085ece">

Stinks that the WebKit people couldn't get the error message to say *which* property was readonly, that would have made it so much more obvious from the beginning...

**Comment by lajbel** [comment]
we probably should change it

**Comment by dragoncoder047** [comment]
My suggestion would be "navigat***or***" because that's what the component makes the object into, and the docs for it use that language too

**Comment by dragoncoder047** [comment]
gosh, whoops, never mind, that one conflicts with an even importanter property!!

**Comment by mflerackers** [comment]
Yes, navigator was my first choice, but I couldn't use it due to that reason. That's why I took navigation.
We had the same problem with anchor, which was called origin originally.
