### ISSUE TITLE
bug: error screen errors out when error is not an Error

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#299]
...and yes, I did put "error" into the title four times!

# Describe the bug

Some event handlers have the feature that when they throw a Javascript error, the game halts with a big blue screen showing the error message.

However, I noticed (by accident) that if the thrown error isn't actually an instance of the Javascript Error class (I occasionally insert `throw "blooey!"` into my code to stop it prematurely), then the code that attempts to display the error itself throws an error and the game halts but to a blank black screen. The error from the dev tools console is `Error: formatText() requires property "text".` and it keeps getting spammed in a loop.

## Version

Whatever's in the kaplayground. Also, bleeding edge master version (`npm i https://github.com/kaplayjs/kaplay`)
## To Reproduce

Put this in kaplayground. Open browser dev tools console. Set `notErrorError` to false to see the normal error screen, or to true to see the brokenness if a string is thrown.
```js
const notErrorError = true;

kaplay();
add([pos(10, 10), rect(10, 10), body(), area(), color("#ff0000"), "A"]);
add([pos(10, 30), rect(10, 10), body({ isStatic: true }), area(), color("#ffff00"), "B"]);
setGravity(200);
onCollide("A", "B", () => {
    if (notErrorError) throw "blooey!" // error 1: not an Error object
    else kaplay.foo(); // error 2: is an Error object
});
```

## Expected behavior

The normal blue error screen displays in both cases with the error message.

## Screenshots

with notErrorError = false:
<img width="1094" alt="Screenshot 2024-08-02 at 3 35 33 PM" src="https://github.com/user-attachments/assets/eee705a5-04a0-4243-86ba-6a41b2a1bfa3">

with notErrorError = true:
<img width="1093" alt="Screenshot 2024-08-02 at 3 36 23 PM" src="https://github.com/user-attachments/assets/706c94f8-b20a-4f3f-9257-2ee4ecbd761a">

**Comment by lajbel** [comment]
PR made!
