### ISSUE TITLE
feat: event when an object is stomped on or headbutted (reflected forms of `onGround` and `onHeadbutt`)

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#300]
There's events for when an object hits the floor (`onGround`) and hits the ceiling (`onHeadbutt`). Where are the equivalents for the thing that was hit (i.e. `onStomped` and `onHeadbutted`)?

I'm making a button object that will react when it a falling object (which may or may not be the player) lands on it from above, and for the event handler that makes the stomped-on button react to the stomp, it doesn't make much sense to attach it to the thing that's falling (by tag or otherwise)...

**Comment by lajbel** [comment]
let me know if it looks good
