### ISSUE TITLE
feat: Stereo pan option for `play()`

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#304]
We already have a volume option for `play()`ing a sound. Can stereo pan be added? There is a web audio node to handle this, it just needs to be put in the pipeline.

This would be useful when a sound is triggered by some physical action, and it would make sense to have the sound appear to come from the location of that action. For example, if an enemy spawned offscreen to the left, the player could be cued that it is to the left by the spawn sound coming from the left speaker. (This is particularly evident when you are using headphones.)

**Comment by amyspark-ng** [comment]
sounds like a cool feature
