### ISSUE TITLE
bug: possible to go through colliders when alt-tabbing away from browser during movement

### ISSUE THREAD

**Issue by riidom** [kaplayjs/kaplay#308]
### A clear and concise description of what the bug is.

While pressing arrow-left and colliding with the outer boundary collider, go out of browser with alt-tab, and then switch back to browser again - character is on other side of the collider.

### What version are you running?

"^3000.1.17"

### Steps to reproduce the behavior:

1. Set up a scene with colliders and a movable object
2. Repeat the alt-tab procedure mentioned above

### A clear and concise description of what you expected to happen.

It shouldnt be possible to pass the collider like that.

### If applicable, add screenshots to help explain your problem.

How the scene is set up:

![image](https://github.com/user-attachments/assets/d23ef1fd-f4c1-40c6-b65f-12628d482284)

How it looks like afterwards:

![image](https://github.com/user-attachments/assets/d0c62fff-e039-42ed-b791-6fe264769e9f)

**Comment by lajbel** [comment]
can you try master?

**Comment by riidom** [comment]
Bug still there unfortunately.

Just to doublecheck: I changed the dependency in my package.json to `"kaplay": "kaplayjs/kaplay"`, deleted node_modules and run npm install.

I also noticed, that the bug can be reproduced on: https://play.kaplayjs.com/?example=collision (use the ground tile).

**Comment by mflerackers** [comment]
I don't think using Kaplay is master though. You need to use the git npm.

**Comment by riidom** [comment]
Could you detail that a little bit? Npm is not my strongest suit unfortunately:)

**Comment by mflerackers** [comment]
npm i github:kaplayjs/kaplay

**Comment by riidom** [comment]
This gives me trouble, I get:
```
42 error code 128
43 error An unknown git error occurred
44 error command git --no-replace-objects ls-remote ssh://git@github.com/kaplayjs/kaplay.git
45 error git@github.com: Permission denied (publickey).
```
If this turns out to be complicated, we could as well wait until next release, and I will check it again then, and comment here or open new issue, what do you think?

I mostly think this is something that I wouldn't want to confront players with on a released game, but otherwise it's not a development show-stopper. But if you have a good idea what the above problem is about, give me a hint and I try that.

**Comment by lajbel** [comment]
let me release a new version

**Comment by riidom** [comment]
Thanks for the release! Bug is still there, though.

**Comment by lajbel** [comment]
Now?

**Comment by lajbel** [comment]
Would be cool also if we got a reproducible example

**Comment by riidom** [comment]
This kaplayground example does it too: https://play.kaplayjs.com/?example=collision

Collide with the ground tile, keep pressing the direction key that moves you towards the ground tile, then alt-tab twice and you are on the other side of the ground tile.

**Comment by lajbel** [comment]
We can't repro on OSX and Ubuntu, is a windows exclusive problem? Can you test using the version in master?

**Comment by lajbel** [comment]
I think this error is very specific. Maybe the current fix is pausing game on window toggling, but that may be on the user side. Re open if you don't think that
