### ISSUE TITLE
bug: raycastShape example is weirding out

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#323]
This is the raycastShape example:

<img width="151" alt="Screenshot 2024-08-05 at 12 16 39 PM" src="https://github.com/user-attachments/assets/7e84ca07-58b7-4f4c-9650-49f001418032">

Circle's reflection is okay. So are all the other polygons.

However, the ellipse reflects the beam straight out the normal and makes the beam infinitely long, even though it computes the normal correctly (the blue line). Then this glitched beam tunnels through the circle and "reflects" off the wrong side of the circle (red dot).

Version is whatever is in the kaplayground right now, it says `VERSION == "3001.0.0"`.

**Comment by mflerackers** [comment]
Fixed
