### ISSUE TITLE
bug: raycast not working?

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#324]
put in kaplayground:

```js
kaplay();

const level = addLevel([
    "a",
], {
    tileHeight: 100,
    tileWidth: 100,
    tiles: {
        a: () => [
            rect(32, 32),
            area(),
            color(RED),
        ],
    }
});
try {
    level.raycast(vec2(50, 50), vec2(-50, -50));
} catch (e) {
    debug.error(e.stack);
    throw e;
}
```

you get error:
```
Uncaught TypeError: Cannot set properties of null (setting 'object')
    at VM282 about:srcdoc:56:14355
    at raycastGrid (VM282 about:srcdoc:2:22862)
    at Object.raycast (VM282 about:srcdoc:56:14162)
    at VM283 about:srcdoc:18:11
```

source map points to `hit` is null here:

https://github.com/kaplayjs/kaplay/blob/de782776a10b3abab6d5145c774095b63dcf8aed/src/game/level.ts#L437-L438

am I calling something wrong or is `raycast` broken?

**Comment by mflerackers** [comment]
Fixed

**Comment by dragoncoder047** [comment]
I'm still having trouble getting the raycast method *of a level object* to work. What are the origin and direction, as well as the `point` of the result relative to? And does it only look at objects that are children of the level?

**Comment by mflerackers** [comment]
Yes, I copied the raycasting code from one of my own projects when I was still using kaboom. I forgot the object raycast at the time I added it to kaplay until someone reminded me. But I didn't test that. Of course it needs to use the original origin. The scaled origin is only to raycast the 2d voxels.

**Comment by dragoncoder047** [comment]
Yeah, my test in the OP is a lousy test of the raycast, since it only tests if the function returns without error, it doesn't check that it got the right answer!

**Comment by mflerackers** [comment]
Also look at mazeRaycastedLight.js for an example.

**Comment by dragoncoder047** [comment]
> Also look at mazeRaycastedLight.js for an example.

Well it kind of helped, kind of made things worse. I added `tile({isObstacle: true})` to all of the tiles I wanted to get hit by the raycast, and now I can't even get the one weird hit that I captured in the above screenshot.

It boils down to: I call

```js
world.raycast(
    player.worldPos(),
    cursor.worldPos().sub(player.worldPos()).unit()
);
```
and get null.

Also, I looked at mazeRaycastedLight example and noticed that if you add `outline: { color: RED, width: 4 },` to the draw options for the yellow light polygon at the bottom, the yellow fill goes away, and only half of an outline shows.

**Comment by mflerackers** [comment]
But why worldpos? The raycast in level takes an origin relative to the level, not the world.
Use a join with the outline. outline: { color: RED, width: 4, join: "bevel" } If you don't use it, it goes to old polygon drawing code which is there for compatibility reasons, but doesn't work for all cases. It will be removed in 4000.

**Comment by dragoncoder047** [comment]
> But why worldpos? The raycast in level takes an origin relative to the level, not the world.

The level is at (0, 0), so that shouldn't change anything unless there's some scaling.

I see you changed the raycast function to use the right origin internally, that might make it work. I ended up changing my code to do a "manual raycast" be getting all the objects it's concerned about, getting `worldArea()`, and then checking to see if the area collides with a line drawn between the center of the player and the center of the cursor. It's actually faster than calling raycast for what I'm doing, so I'm not using raycast anymore. 

> Use a join with the outline. outline: { color: RED, width: 4, join: "bevel" } If you don't use it, it goes to old polygon drawing code which is there for compatibility reasons, but doesn't work for all cases.

Will try that, thanks!
