### ISSUE TITLE
bug: game appears sped up

### ISSUE THREAD

**Issue by amyspark-ng** [kaplayjs/kaplay#334]
## **Describe the bug**
Eli helped me to port my game to vite, now everytime i open the game it's speed up to 1.2x, and i can't seem to use pause (f8) or slow it down to 1x because everytime i press a speed debug key it adds/subs 4

## **Version**
v3001.0.0-alpha20

**Comment by lajbel** [comment]
As we talked, is probably a bug in vite or your setup
