### ISSUE TITLE
bug: Text rendered through add() or drawText is cropped.

### ISSUE THREAD

**Issue by Hellorelei** [kaplayjs/kaplay#337]
### Steps to reproduce the behavior:

1. Use the Shantell Sans font in medium, .ttf
2. Create text via add() or drawText()

### 
<img width="207" alt="Screenshot of text test!. Bottom is cropped." src="https://github.com/user-attachments/assets/c2ef7c60-e71f-4857-ad51-d943fbe78b6a">

<img width="207" alt="Screenshot of letters a-z. Bottom is cropped." src="https://github.com/user-attachments/assets/09fdc753-da6c-4554-a610-9fa9ba93b573">

## **Example code**

```js
k.onDraw(() => {
    k.drawText({
        text: "abcdefg\nhijklmn\nopqrstu\nvwxyz!",
        size: 48,
        font: "Shantell Sans",
        pos: k.mousePos(),
        width: 120
    })
})
```

**Comment by Hellorelei** [comment]
I'm wondering now if it's not just something with my browser, as the default font presents the same issue:

**Comment by Hellorelei** [comment]
Alright I did more testing, it seems it may actually be a kaplay-Safari issue and not a font-specific issue. Friend with Firefox on their laptop have no issues with displaying Shantell Sans when connecting to the server. Should I edit the issue with the new info, or close it and open a new one for Safari support?

**Comment by mflerackers** [comment]
It is a kaplay issue, the sprite map builder for ttf text just uses the size for height, which is wrong.
```ts
c2d.font = `${font.size}px ${fontName}`;
c2d.textBaseline = "top";
c2d.textAlign = "left";
c2d.fillStyle = "#ffffff";
const m = c2d.measureText(ch);
let w = Math.ceil(m.width);
if (!w) continue;
let h = font.size;
```
It works for a lot of fonts, but it won't for all. It should calculate the height from the text measurement.

**Comment by lajbel** [comment]
fixed!
