### ISSUE TITLE
bug: debug view's area outlines are also stretched by AreaComp.area.scale

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#338]
so I wrote some code to merge the ground tiles in the tile map of my platformer's levels... if there are two adjacent ground tiles A and B, it stretches and offsets A's area so it encloses both of them, then it removes the area component on B.

However, I noticed something weird when turning on the debug inspect view to see if my code was working: the outlines of the objects are also stretched according to the scale of the area. It looks as though the outline is drawn first on an offscreen texture, and then the image of the outline is then scaled according to the area scale. But shouldn't the outline be drawn the same width regardless of the scale so that it doesn't obscure anything unintentionally?

(To see what's happenning: put this in the kaplayground:

```js
kaplay({ scale: 2 });

const obj = add([
    rect(16, 16),
    color(RED),
    pos(100, 100),
    area()
]);

obj.area.scale.x = 20;

debug.inspect = true;
```
)

If this outline-stretching was historically used to (crudely) indicate the object's scale, it might not be necessary anymore now that the debug view can show the scale on the area component by hovering over the object.

**Comment by amyspark-ng** [comment]
area has always been displayed by the debug inspect tooltip and as far as I'm aware the outline also has been stretched to match the area of the scale, i personally don't see what's the issue with it

**Comment by dragoncoder047** [comment]
> i personally don't see what's the issue with it

My code ends up stretching the area by 20-30x in some places, the outline is normally about 3px wide, but it ends up becoming ~75px wide and obscuring multiple tiles when stretched (my tiles are only 32x32)!

**Comment by JSLegendDev** [comment]
I had the same issue occur. It's really annoying visually!
