### ISSUE TITLE
bug: kaplay thinks its kaboom, it crashes when using text + sprite

### ISSUE THREAD

**Issue by blurymind** [kaplayjs/kaplay#351]
## **Describe the bug**
Using the module import 

I notice two things
- kaplay still registers itself in the window as "kaboom". So I cant kaplay(). I still have to kaboom()
- if you try to add to a scene a sprite and a text object - you get an error message
![image](https://github.com/user-attachments/assets/7999a19a-62dd-4531-83de-9fd0579e5a67)

### A clear and concise description of what the bug is.
The error message is a stopper for me. Kaplay completely crashing by simply using a text and a sprite.

## **Version**
https://unpkg.com/kaplay@3000.1.17/dist/kaboom.js
and 
https://unpkg.com/kaplay@3001.0.0-alpha.21/dist/kaplay.js
### What version are you running?
 tried both
### Steps to reproduce the behavior:

```
      const k = kaboom();
      k.loadSprite("bean", "public/icon.png")
      // define a scene
      k.scene("main", () => {

        // add a text at position (100, 100)
        k.add([
          k.text("ohhimark"),
          // k.pos(200, 100),
          k.sprite("bean"),
        ]);

      });

      // start the game
      k.go("main");
```
If I have only text or only sprite I dont get a crash btw..
## **Expected behavior**

not crash
### A clear and concise description of what you expected to happen.
a sprite and a text object to exist together?

**Comment by UnPolloLoco** [comment]
Sprites and text are two separate types of object, do not try to combine them. You will need two `add()`s for that.

**Comment by mflerackers** [comment]
Most likely you are not using a recent version of kaplay. Kaplay should be exported as can be seen in the playground.
As said, you can't use two draw components on the same object. You need to create a child object for the text.

**Comment by blurymind** [comment]
ah right, sorry I misunderstood this. In that case this ticket can be closed.

Interestingly on the last alpha it can be initiated both via kaboom and kaplay
