### ISSUE TITLE
docs: extent of setCursor

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#386]
Now that we have custom fake mouse objects (#372) it's a bit counterintuitive and maybe a bit wasteful of yet another onUpdate hook to have to write `onUpdate(() => setCursor("none"))` to hide the system cursor.

So I was thinking that the global `setCursor` function could have a second parameter `sticky`, default false, when it is true, it sets the "default" cursor that the canvas cursor gets reset to every frame, instead of the current frame's cursor. Then you could just do `setCursor("none", true)` and let the browser handle constantly hiding the cursor.

I'd open a PR, but I can't find the spot in the code where the cursor gets reset at the end of the frame.

**Comment by amyspark-ng** [comment]
you don't have to do setCursor("none") on update!! that could lag the game i think, you could probably set it at the start and that'd work well

**Comment by dragoncoder047** [comment]
> you could probably set it at the start and that'd work well

Never mind actually, that seems to work. I guess this is a docs issue because the docs for setCursor say:

> `setCursor(style: Cursor): void`
> Set cursor style (check Cursor type for possible values). **Cursor will be reset to "default" every frame** so use this in a per-frame action.

(emphasis mine)

**Comment by amyspark-ng** [comment]
> > you could probably set it at the start and that'd work well
> 
> Never mind actually, that seems to work. I guess this is a docs issue because the docs for setCursor say:
> 
> > `setCursor(style: Cursor): void`
> > Set cursor style (check Cursor type for possible values). **Cursor will be reset to "default" every frame** so use this in a per-frame action.
> 
> (emphasis mine)

**Comment by lajbel** [comment]
Maybe also an option in fakeCursor component?
