### ISSUE TITLE
bug: changes introduced in e0bd34a7f7216d581842e2ae279243e0eb94bf7e break area offset lining up with physical collider

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#416]
I wrote some code to merge adjacent tiles (which I pasted in #381), and then updated to kaplay master, and it suddenly stopped working.

Rolling back to fb324db2a5cd4554cfd2901d9621d430c9c6ca95 fixed it, so must be changes [here](https://github.com/kaplayjs/kaplay/commit/e0bd34a7f7216d581842e2ae279243e0eb94bf7e#diff-86d1b7c17efe64db5a2265dd52974934d32615c3034adfaaec42c7838a71c389R356) that cause the actual physical collider to no longer line up with the drawn area.

**Comment by mflerackers** [comment]
Exactly what kind of collisions don't line up anymore? Raycasts or physics?

**Comment by dragoncoder047** [comment]
> Exactly what kind of collisions don't line up anymore? Raycasts or physics?

Physics. What happens is the player and boxes fall straight through the floor, and the debug hover doesn't use the right area, even though the debug outlines and sprites still render in the same place.

**Comment by dragoncoder047** [comment]
Looking at what `calcTransform` does, it might just end up doing the whole transform *twice*, once for the actual parameters, and again for the `transform` (which is just made to be identical to the transform properties). Dunno why this doesn't affect the rendering...

**Comment by mflerackers** [comment]
calcTransform is correct. Since the pos was changed, the transform needed to be recalculated.

**Comment by mflerackers** [comment]
<img width="720" alt="Screenshot 2024-09-24 at 11 17 38" src="https://github.com/user-attachments/assets/d6a7f01d-4a11-464c-8349-a5823f7fd2af">

To me it looks like scale is happening before offset, so offset gets scaled

**Comment by mflerackers** [comment]
Are you using the latest version? This https://github.com/kaplayjs/kaplay/commit/bd4b9b8c9436d875846f179921e4d7c4ba4988ee should have fixed it I think, as the latest master works with your merge code. The kaplayground is probably using an old version.

**Comment by dragoncoder047** [comment]
I just tried 3923092474f4712b4cb0a9fc34b3b6594a570236 and can't reproduce it... must have been a bug in my code.

> The kaplayground is probably using an old version.

I wasn't using the kaplayground. :shrug:
