### ISSUE TITLE
bug: sticky keys

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#444]
```js
kaplay();

onKeyDown("a", () => debug.log("foo"));
```

1. press a then press cmd or alt
2. release a then release the modifier key
3. the foo keeps getting logged

**Comment by lajbel** [comment]
We determined this only happens when a key + any modifier has as result another key, so internally the key is not released.

**Comment by lajbel** [comment]
There's already a keyCode support on Buttons API, it should help
