### ISSUE TITLE
bug: particles() component's emit() function errors after a particle's lifespan has been expired.

### ISSUE THREAD

**Issue by tristanperrow** [kaplayjs/kaplay#450]
### Steps to reproduce the behavior:

1. Add the particles() component to a game object
2. Emit particles once
3. Wait until the lifespan of at least one particle has passed
4. Emit particles again.

## **Screenshots**

![image](https://github.com/user-attachments/assets/c0950fd7-0cd7-4ad2-930d-db150883d3cf)
![image](https://github.com/user-attachments/assets/f3d23068-a6a4-4fb8-a46a-c46f9cabd9df)

**Comment by lajbel** [comment]
Can you provide an example on KAPLAYGROUND?

**Comment by tristanperrow** [comment]
Was fixed as of `4000.0-alpha.8` due to MF's `fix for particles` commit.
