### ISSUE TITLE
bug: using a list of keys in onKeyDown() runs the key twice

### ISSUE THREAD

**Issue by Desyncfy** [kaplayjs/kaplay#485]
## **Describe the bug**
If you use an array with keys, say ["right", "d"] and put them in the onKeyDown function, it will run the function twice as fast
## **Version**
3001.0.0-beta.6
### Steps to reproduce the behavior:

1. create a new kaplay project
2. add the following code to src/main.js:
```js
let example = 0;

onKeyDown(["right", "d"], () => {
    example++;
    debug.log(example);
});
```
3. run it

## **Expected behavior**
example variable increases the same amount if you hold both of the keys compared to only one of them
## **Screenshots**
N/A

**Comment by lajbel** [comment]
Is how it works, you should take the count by yourself, if not, take a look to buttons api

**Comment by lajbel** [comment]
May I can add an option, also you can use isKeyPressed() in an if, inside an onUpdate

**Comment by dragoncoder047** [comment]
I notice this too, it was super annoying until I figured out what was going on, but there is an easy hackaround:

```ts
// replace:
onKeyDown(["a", "b", "etc"], () => {
    do_stuff();
});
// with:
onUpdate(() => {
    if (isKeyDown(["a", "b", "etc"])) {
        do_stuff();
    }
});
```

Although it would be nice if this didn't happen. The option could be an optional 3rd argument to onKeyDown and friends, iff it is called with [array of input names, callback function, options object] in any order, it does this. The option could be called something like `{ forEach: false }` and default to true, which triggers the existing behavior.

**Comment by imaginarny** [comment]
But itt really is how it works. There is no relation between "right" and "d" and you register one listener for both which will fire if any of them is pressed. So when both are down, both will fire down event and you captured that.

You really need to use buttons api for your use case.

```js
kaplay({
  buttons: {
    right: {
      keyboard: ["right", "d"],
    },
  },
});

let example = 0;

onButtonDown("right", () => {
  example++;
  debug.log(example);
});
```

**Comment by Desyncfy** [comment]
> You really need to use buttons api for your use case.
Yeah, I completely ignored that in the docs and promptly forgot about it. I'll do that instead then. Thanks!
