### ISSUE TITLE
bug: setting loop: true when playing music doesn't set loop

### ISSUE THREAD

**Issue by cobrajs** [kaplayjs/kaplay#527]
### Steps to reproduce the behavior:

1. Load music with `loadMusic('music', '<url>')`
2. Play music with `play('music', { loop: true })`
3. Wait for the music to finish playing the first time through. It should loop, or play again from the start, but it does not.

**Comment by amyspark-ng** [comment]
does this also happen when is loaded using loadSound rather than loadMusic

**Comment by cobrajs** [comment]
Using [this example](https://play.kaplayjs.com/?example=audio), it does loop correctly when using loadSound.

I got it to work locally by adding `el.loop = Boolean(opt.loop);` below [this line](https://github.com/kaplayjs/kaplay/blob/d32447ec8e26ea764a68fd8ac680474e262de30d/src/audio/playMusic.ts#L9), since `playMusic()` doesn't use the AudioPlayOpt the same way that `play()` does.
