### ISSUE TITLE
bug: Collision check not working while animating object scale.

### ISSUE THREAD

**Issue by Mikuz** [kaplayjs/kaplay#529]
If you use animate(), and animate scale of object, the collision check is working only for original size, the size changed by animation doe's not work. 
If you animate pos/angle => collison works.

**How to replicate:**
Go to:  https://play.kaplayjs.com/?example=collision
Add: animate(), to object player
Add:
```
         player.animate("scale", [1, 3], {
                        duration: 1,
                    });
```

**Comment by mflerackers** [comment]
Scale is not a number, it is a vector. So your code breaks the scale property and thus the game.

**Comment by mflerackers** [comment]
If you use

player.animate("scale", [vec2(1), vec2(3)], {
                        duration: 1,
                   });

it works as expected

**Comment by Mikuz** [comment]
Thank You!
Rookie mistake by me. 
Just started using Kaplay
