### ISSUE TITLE
bug: input events don't catch errors

### ISSUE THREAD

**Issue by amyspark-ng** [kaplayjs/kaplay#74]
## **Describe the bug**
When you have an error, it usually is met with a blue screen that tells you what the error is, this doesn't happen in input events

## **Version**
What version are you running?
kaboom v3000

**Comment by mflerackers** [comment]
A possible quick fix would be to run processInput within the try/catch

app.run:
```ts
action(()=>{processInput()});
```

kaplay:
```ts
app.run((processInput) => {
        try {
           processInput()
```
