### ISSUE TITLE
feat: Improved hitboxes and collisions

### ISSUE THREAD

**Issue by sharmnten** [kaplayjs/kaplay#81]
**The problem**
I'm always frustrated when in my game, the hit-boxes of various game objects are slightly to large, resulting in the player being able to float off corners.

**The solution**
I would like Improved hit boxes and collision recognition in kaplay.

**Additional context**
![image](https://github.com/marklovers/kaplay/assets/115847442/9f043d5d-e29e-45e1-80d2-cfd5815ba15b)

**Comment by niceEli** [comment]
can you enable debug to show the hitboxes (F1 key or `debug.inspect = true`)

**Comment by sharmnten** [comment]
<img width="389" alt="image" src="https://github.com/marklovers/kaplay/assets/115847442/ad00652f-5cda-4ea5-a1ef-94f741ff9fe2">

**Comment by niceEli** [comment]
this happens because of the bounding box for the hitbox being the size of the sprite

if you would like to customize it then you can change the size using the the body component API
[https://kaplayjs.com/reference/#body](https://kaplayjs.com/reference/#body)

**Comment by lajbel** [comment]
Circle areas were added on v4000
